import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os
import argparse

def plot_class_distribution(csv_path, output_prefix):
    """Generates a bar chart showing verbs matched by each class."""
    if not os.path.exists(csv_path):
        print(f"Warning: {csv_path} not found. Skipping class distribution plot.")
        return

    df = pd.read_csv(csv_path)
    if df.empty:
        return

    # Prepare data for plotting
    df_melted = df.melt(id_vars='class', 
                        value_vars=['strict_ending', 'strict_full', 'loose_ending', 'loose_full'],
                        var_name='Match Type', value_name='Count')

    def create_plot(data, suffix):
        plt.figure(figsize=(12, 8))
        sns.barplot(data=data, x='class', y='Count', hue='Match Type')
        plt.title(f'Verb Matches per Class ({suffix})')
        plt.xticks(rotation=45, ha='right')
        plt.tight_layout()
        plt.savefig(f'{output_prefix}_{suffix.lower()}.png')
        plt.close()

    # Full version
    create_plot(df_melted, 'Full')

    # Filtered version (only classes with at least one match in any category)
    active_classes = df[(df[['strict_ending', 'strict_full', 'loose_ending', 'loose_full']] > 0).any(axis=1)]['class']
    df_filtered = df_melted[df_melted['class'].isin(active_classes)]
    if not df_filtered.empty:
        create_plot(df_filtered, 'Filtered')

def plot_verb_coverage(json_path, output_path):
    """Generates a bar chart for verb coverage summary."""
    if not os.path.exists(json_path):
        print(f"Warning: {json_path} not found. Skipping verb coverage plot.")
        return

    with open(json_path, 'r') as f:
        data = json.load(f)

    # Convert to DataFrame
    rows = []
    for combo, counts in data.items():
        for cat, val in counts.items():
            rows.append({'Combination': combo, 'Coverage': cat, 'Count': val})
    
    df = pd.DataFrame(rows)

    plt.figure(figsize=(10, 6))
    sns.barplot(data=df, x='Combination', y='Count', hue='Coverage')
    plt.title('Verb Coverage Summary')
    plt.xticks(rotation=15)
    plt.tight_layout()
    plt.savefig(output_path)
    plt.close()

def plot_near_miss_heatmap(csv_path, output_prefix):
    """Generates a heatmap of pass rates for stem-final checks."""
    if not os.path.exists(csv_path):
        print(f"Warning: {csv_path} not found. Skipping near-miss heatmap.")
        return

    df = pd.read_csv(csv_path)
    if df.empty:
        return

    # We want to plot the rates. Columns: present_rate, imperfective_rate, etc.
    rate_cols = [c for c in df.columns if c.endswith('_rate')]
    
    def create_heatmap(data, suffix):
        # Set index to class + strictness for better labeling
        plot_df = data.copy()
        plot_df['label'] = plot_df['class'] + " (" + plot_df['strictness'] + ")"
        plot_df = plot_df.set_index('label')[rate_cols]
        
        # Shorten column names for the plot
        plot_df.columns = [c.replace('_rate', '') for c in plot_df.columns]

        plt.figure(figsize=(12, min(20, len(plot_df) * 0.4 + 2)))
        sns.heatmap(plot_df, annot=True, cmap="YlGnBu", vmin=0, vmax=1)
        plt.title(f'Stem-Final Pass Rates ({suffix})')
        plt.tight_layout()
        plt.savefig(f'{output_prefix}_{suffix.lower()}.png')
        plt.close()

    # Full version
    create_heatmap(df, 'Full')

    # Filtered version: classes with at least one match (match_count > 0)
    # Actually near_misses.csv only includes those with ending matches, 
    # but some might have 0 pass rates across the board.
    # The user said "excludes items with zero or near-zero values".
    # Let's exclude rows where the sum of rates is very small or match_count is 0.
    df_filtered = df[df['match_count'] > 0]
    if not df_filtered.empty:
        create_heatmap(df_filtered, 'Filtered')

def run_all_visualizations():
    os.makedirs('artifacts', exist_ok=True)
    
    print("Generating Class Distribution plots...")
    plot_class_distribution('artifacts/class_match_counts.csv', 'artifacts/class_distribution')
    
    print("Generating Verb Coverage plot...")
    plot_verb_coverage('artifacts/verb_coverage.json', 'artifacts/verb_coverage.png')
    
    print("Generating Near-Miss Heatmap plots...")
    plot_near_miss_heatmap('artifacts/class_near_misses.csv', 'artifacts/near_miss_heatmap')

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate visualizations for match data.")
    # The user said "no need to add a flag to the cli" for --hide-clutter, 
    # they want both generated by default.
    args = parser.parse_args()
    
    run_all_visualizations()
    print("Visualizations saved to artifacts/")
